baseURL = "https://dohq.github.io/presentation"
languageCode = "en-us"
copyright = "2017 R.Maejima"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
highlight_theme = "solarized-dark"
slide_number = true
transition = "concave"
